# Generated by Django 5.0.6 on 2024-05-11 13:15

import django.db.models.deletion
import hyeeum.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Library',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('book_count', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('user_name', models.CharField(max_length=100)),
                ('user_tag', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('birth', models.DateField()),
                ('alignment', models.CharField(max_length=100)),
                ('template', models.BooleanField(default=False)),
                ('polite', models.BooleanField(default=False)),
                ('library_count', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('image', models.ImageField(upload_to=hyeeum.models.upload_to_image)),
                ('comment', models.TextField(blank=True)),
                ('detail_story', models.TextField(blank=True)),
                ('emotion', models.CharField(choices=[('기쁨', '기쁨'), ('화남', '화남'), ('슬픔', '슬픔'), ('즐거움', '즐거움')], max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('library_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hyeeum.library')),
            ],
        ),
        migrations.CreateModel(
            name='Statistics',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('happiness', models.IntegerField(default=0)),
                ('aggro', models.IntegerField(default=0)),
                ('sadness', models.IntegerField(default=0)),
                ('joy', models.IntegerField(default=0)),
                ('gpt_comment', models.CharField(default='', max_length=500)),
                ('library_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hyeeum.library')),
            ],
        ),
        migrations.AddField(
            model_name='library',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hyeeum.user'),
        ),
    ]
