# Generated by Django 5.0.6 on 2024-05-11 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hyeeum', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_tag',
            field=models.IntegerField(unique=True),
        ),
    ]
