# Generated by Django 5.0.6 on 2024-05-11 14:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hyeeum', '0002_alter_user_user_tag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='library_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='books', to='hyeeum.library'),
        ),
        migrations.AlterField(
            model_name='library',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='librarys', to='hyeeum.user'),
        ),
        migrations.AlterField(
            model_name='statistics',
            name='library_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='statistics', to='hyeeum.library'),
        ),
    ]
