# Generated by Django 5.0.6 on 2024-05-15 12:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hyeeum', '0004_alter_book_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={},
        ),
    ]
